### ISSUE TITLE
DELETE ? 

### ISSUE THREAD

**Issue by zteeed** [AdRCS-2018-dev/Quadrabang2018#2]
je peux delete le projet ou t'en a besoin ?

**Comment by TheoBa** [comment]
Chaud pour pas le delete si possible ! Au moins un an hihihi

Le mar. 5 févr. 2019 à 19:07, Aurélien Duboc <notifications@github.com> a
écrit :

**Comment by zteeed** [comment]
ok si t'en as besoin pour l'an prochain je vais proprifier deux trois trucs et simplifier pour faire un déploiement clé en main
